# Programming Assignment 8

In [2]:
import numpy as np

In [5]:
# Q.1.

def add_two_matrix(A, B):
    '''
    A and B are two 2D lists converted to numpy 2D arrays and added
    Return type is numpy array
    '''
    nA = np.array(A)
    nB = np.array(B)
    if nA.shape == nB.shape:
        return nA + nB
    else:
        print("Inputs do not have the same shape")
        return None

In [6]:
add_two_matrix([[1,2], [3,4]], [[-1,-2], [-3, -4]])

array([[0, 0],
       [0, 0]])

In [11]:
# Q.2.

def mul_two_matrix(A, B):
    '''
    A and B are two 2D lists converted to numpy 2D arrays and multiplied (matrix multiplication)
    Return type is numpy array
    '''
    nA = np.array(A)
    nB = np.array(B)
    try:
        assert nA.shape[1] == nB.shape[0]
        return np.dot(nA, nB)
    except Exception as e:
        print(e)
        return None

In [13]:
mul_two_matrix([[1,2], [3,4], [5,6]], [[-1,-2], [-3, -4]])

array([[ -7, -10],
       [-15, -22],
       [-23, -34]])

In [14]:
# Q.3.

def transpose(A):
    nA = np.array(A)
    return nA.T

In [15]:
transpose([[1,1,1], [2,2,2], [3,3,3]])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [17]:
# Q.4.

def sort_words(lst):
    '''
    lst: a list of words (strings)
    returns sorted list
    '''
    return sorted([w.lower() for w in lst])


In [19]:
sort_words(["apple", "Microsoft", "Tesla", "facebook", "Google"])

['apple', 'facebook', 'google', 'microsoft', 'tesla']

In [25]:
# Q.5.

def remove_punc(s):
    numbers = "0123456789"
    new_s = ""
    for c in s:
        if c not in numbers:
            n = ord(c)
            if (n<65) or (n > 90 and n < 97) or (n > 122):
                continue
        new_s += c
    return new_s

In [26]:
remove_punc("abc123@email.com")

'abc123emailcom'